# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'YiDingYing' do

#第三方

#无依赖

#有依赖

#依赖

pod 'YXCommon', :path => '../YXCommon/'
pod 'Creditease', :path => '../Creditease'

end

target 'YiDingYingTests' do

end

